### ISSUE TITLE
安装webpack-dev-server之后运行，总是提示找不到webpack/hot/dev-server

### ISSUE THREAD

**Issue by jasonleft** [vikingmute/webpack-for-fools#2]
我是按照第一篇教程一步一步进行的，安装了全局的webpack，和全局的webpack-dev-server，然后在package.json里添加了scripts：start: webpack-dev-server --hot --line，运行npm start，就是报错，页面也出不来。

```
ERROR in multi main
Module not found: Error: Cannot resolve module 'webpack/hot/dev-server' in D:\My
Web\webpack
 @ multi main
webpack: bundle is now VALID.
```

**Comment by vikingmute** [comment]
@jasonleft 能把你的config代码贴上来看看不

**Comment by jasonleft** [comment]
webpack.config.js

```
var path = require('path');
var HtmlWebPackPlugin = require('html-webpack-plugin');

var ROOT_PATH = path.resolve(__dirname);
var APP_PATH = path.resolve(ROOT_PATH, 'app');
var BUILD_PATH = path.resolve(ROOT_PATH, 'build');

module.exports = {
    entry: APP_PATH,
    output: {
        path: BUILD_PATH,
        filename: 'bundle.js'
    },
    devServer: {
        historyApiFallback: true,
        hot: true,
        inline: true,
        progress: true,
    },
    plugins: [
        new HtmlWebPackPlugin({
            title: 'Hello World App'
        })
    ],
};
```

package.json:

```
{
  "name": "webpack",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "dependencies": {},
  "devDependencies": {
    "html-webpack-plugin": "^1.7.0",
    "webpack-dev-server": "^1.14.0"
  },
  "scripts": {
    "start": "webpack-dev-server --hot --inline"
  },
  "author": "",
  "license": "ISC"
}

```

**Comment by jasonleft** [comment]
我的npm版本3.5.2， node版本4.0.0，没有使用express之类的框架，纯学习项目，webpack和webpack-dev-server是安装的全局的，因为我发现在package.json里的scripts要调用的东西，如果不是全局的，就找不到命令，另外了解到npm 3之后，npm包的依赖都是以平级展示，以前都是树形的文件夹结构，目前还在找原因中，求指点一二，webpack总是挡在这一步，还木有入门。

**Comment by vikingmute** [comment]
@jasonleft 建议首先把node版本和npm版本都降下来 npm不要用3.0.0以上的 node版本也降低 高版本node据反馈来看都会有问题  把node_modules文件夹都删除再重新安装一下 我今天会做一些node版本的实验

**Comment by jasonleft** [comment]
@vikingmute 好的，我再试试低版本的

**Comment by li9269391** [comment]
@jasonleft 先执行命令 webpack 再 npm start

**Comment by li9269391** [comment]
如果修改默认端口不能解决问题，可以尝试，同样是进入文件 \node_modules\webpack-dev-server\bin\webpack-dev-server.js 找到里面的 "localhost"（一共有2处） 替换成本地ip地址，我的就是这样解决问题，之前试过N个nodejs版本都不行，而且家里的笔记本可以，就公司的要改。

**Comment by li9269391** [comment]
不对，好像你的问题和我不一样

**Comment by jasonleft** [comment]
应该先在全局安装1份webpack， 1份webpack-dev-server，再在本地安装一个webpack，再使用配置文件编译就可以了
