### ISSUE TITLE
source-map的用法

### ISSUE THREAD

**Issue by freeyiyi1993** [vikingmute/webpack-for-fools#6]
https://github.com/vikingmute/webpack-for-fools/blob/master/entries/chapter-2.md 这里配置了查看sourcemap的选项，可是样式文件不是被打入页面了么，怎么查看.map文件啊

**Comment by vikingmute** [comment]
解决 感谢建议 请看我最新的提交
https://github.com/vikingmute/webpack-for-fools/commit/7f16e5cee3f9502538e5f88c60acc8cb2ffc2926

**Comment by freeyiyi1993** [comment]
多谢，先谢在看
